#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../../../.." && pwd)"
INTEGRATION_LINUX_DIR="${REPO_ROOT}/tests/integration/linux"
ARTIFACTS_DIR="${INTEGRATION_LINUX_DIR}/artifacts"
STATE_DIR="/tmp/vpn_agent_integration"
ENV_FILE="${ARTIFACTS_DIR}/.env.generated"

NS_A="vpn-ns-a"
NS_B="vpn-ns-b"
VETH_A_HOST="veth-vpn-a-host"
VETH_A_NS="veth-vpn-a"
VETH_B_HOST="veth-vpn-b-host"
VETH_B_NS="veth-vpn-b"

NS_A_HOST_IP="172.31.201.1"
NS_A_AGENT_IP="172.31.201.11"
NS_A_CIDR="24"

NS_B_HOST_IP="172.31.202.1"
NS_B_AGENT_IP="172.31.202.11"
NS_B_CIDR="24"

CONTROL_PLANE_PORT="4000"

run_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

require_cmd() {
  local cmd="$1"
  command -v "${cmd}" >/dev/null 2>&1 || {
    echo "Missing required command: ${cmd}" >&2
    exit 1
  }
}

namespace_exists() {
  local ns="$1"
  run_root ip netns list | awk '{print $1}' | grep -qx "${ns}"
}

link_exists() {
  local ifname="$1"
  run_root ip link show "${ifname}" >/dev/null 2>&1
}

write_env_file() {
  cat >"${ENV_FILE}" <<EOF
# Auto-generated by setup_env.sh
NS_A=${NS_A}
NS_B=${NS_B}
NS_A_AGENT_IP=${NS_A_AGENT_IP}
NS_B_AGENT_IP=${NS_B_AGENT_IP}
CONTROL_PLANE_URL_A=http://${NS_A_HOST_IP}:${CONTROL_PLANE_PORT}/_mock/openapi
CONTROL_PLANE_URL_B=http://${NS_B_HOST_IP}:${CONTROL_PLANE_PORT}/_mock/openapi
STATE_DIR=${STATE_DIR}
EOF
}
